import type { Metadata } from "next";
import { Bowlby_One_SC, DM_Mono } from "next/font/google";
import { ConvexClientProvider } from "./ConvexClientProvider";
import { CivicAuthProvider } from "@civic/auth-web3/nextjs";
import { SolanaProvider } from "./SolanaProvider";
import { Toaster } from "@/components/ui/sonner";

import "./globals.css";

const dmMono = DM_Mono({
  variable: "--font-dm-mono",
  subsets: ["latin"],
  weight: "500",
  display: "swap",
});

const bowlby = Bowlby_One_SC({
  variable: "--font-bowlby-sc",
  subsets: ["latin"],
  weight: "400",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <CivicAuthProvider>
        <ConvexClientProvider>
          <SolanaProvider>
            <body
              className={`${bowlby.variable} ${dmMono.variable} antialiased font-mono font-medium text-zinc-800`}
            >
              {children}
              <Toaster className="dark" />
            </body>
          </SolanaProvider>
        </ConvexClientProvider>
      </CivicAuthProvider>
    </html>
  );
}
